// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okwcolaolnuzarfwgqvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rd2NvbGFvbG51emFyZndncXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTQ4NDksImV4cCI6MjA1NzE5MDg0OX0.CowDhzFtMHEo5Y9lTMycf_smdXsUSpHAjeOtlEwHmfE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);