// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uiuwrywmvgtguirichcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpdXdyeXdtdmd0Z3VpcmljaGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTMzOTIsImV4cCI6MjA1NzE4OTM5Mn0.D8gIvZhemw1qz67APnyAINUcGvBwcSVSn77R7CPXy8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);